### ISSUE TITLE
Wrong arguments in the memset() function call

### ISSUE THREAD

**Issue by kemonats** [AVSystem/Anjay-zephyr-client#1]
In the files:
[demo/src/utils.c](https://github.com/AVSystem/Anjay-zephyr-client/blob/0f1a92916ab9ee03762c7226f55d30954d3dac37/demo/src/utils.c#L26)
[ei_demo/src/utils.c](https://github.com/AVSystem/Anjay-zephyr-client/blob/0f1a92916ab9ee03762c7226f55d30954d3dac37/ei_demo/src/utils.c#L26)
[minimal/src/utils.c](https://github.com/AVSystem/Anjay-zephyr-client/blob/0f1a92916ab9ee03762c7226f55d30954d3dac37/minimal/src/utils.c#L26)
the `memset()` function calls should probably be like this:
```
memset(out_id->value, 0, sizeof(out_id->value));
```

**Comment by Mierunski** [comment]
Hi!
Thanks for noticing, will fix the typo soon.

Best regards,
Mieszko

**Comment by kFYatek** [comment]
This is fixed in the today's release. We hope it didn't cause too much inconvenience.
